openapi: 3.0.0
info:
  title: Kigali Public Library APs
  description: >
    kigali public library APIs developed in nodeJS
  version: 1.0.0

paths:
  /user:
    put:
      tags:
        - user
      description: Creates a new user with the specified attributes
      summary: Create user
      operationId: createuser
      requestBody:
        description: user
        required: true
        content:
          application/json:
            schema:
              title: user
              allOf:
                - $ref: "#/components/schemas/user"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/user_id"
                  - $ref: "#/components/schemas/user"

  /user/{id}:
    get:
      tags:
        - user
      description: Gets a specific user by ID
      summary: Get user
      operationId: fetchuser
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/user_id"
                  - $ref: "#/components/schemas/user"
    post:
      tags:
        - user
      description: Updates a specific user
      summary: Update user
      operationId: updateuser
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        description: user
        required: true
        content:
          application/json:
            schema:
              title: user
              allOf:
                - $ref: "#/components/schemas/user"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/user_id"
                  - $ref: "#/components/schemas/user"
    delete:
      tags:
        - user
      description: Deletes the user by ID
      summary: Delete user
      operationId: removeuser
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/user_id"

  /users/all:
    get:
      tags:
        - Search
      description: Gets all the users
      summary: Get all users
      operationId: fetchAllusers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/users"

  /users/by-last-name/{last_name}:
    get:
      tags:
        - Search
      description: Gets users by last name
      summary: Get users by last name
      operationId: fetchusersByLastName
      parameters:
        - $ref: "#/components/parameters/last_name"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/users"

  /users/old-enough-to-drink-in-america:
    get:
      tags:
        - Search
      description: Gets users that are 21+
      summary: Get users of drinking age
      operationId: fetchDrinkingusers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/users"

  /users/non-verified:
    get:
      tags:
        - Search
      description: Gets users that are *not* verified
      summary: Get non-verified users
      operationId: fetchNonVerifiedusers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/users"

  /users/verified-drinkers-with-last-name/{last_name}:
    get:
      tags:
        - Search
      description: Gets users that are verified, 21+, and have a matching last name
      summary: Get oddly specific set of users
      operationId: fetchVerifiedDrinkersByLastName
      parameters:
        - $ref: "#/components/parameters/last_name"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/users"

  /users/with-statement-containing/{text}:
    get:
      tags:
        - Search
      description: Gets users with useral statement matching the offered text
      summary: Get users with words matching useral statement
      operationId: fetchusersWithStatement
      parameters:
        - $ref: "#/components/parameters/text"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/users"

  /users/near/{longitude},{latitude}/radius/{radius}:
    get:
      tags:
        - Search
      description: Gets users near a location
      summary: Get users near location
      operationId: fetchusersNearLocation
      parameters:
        - $ref: "#/components/parameters/longitude"
        - $ref: "#/components/parameters/latitude"
        - $ref: "#/components/parameters/radius"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/users"

  /user/{id}/location/{longitude},{latitude}:
    patch:
      tags:
        - Location
      description: Updates the user's location
      summary: Update user's location
      operationId: updateuserLocation
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/longitude"
        - $ref: "#/components/parameters/latitude"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/user_id"
                  - $ref: "#/components/schemas/user_location"

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: The ID of the user to interact with
      schema:
        $ref: "#/components/schemas/id"
    last_name:
      name: last_name
      in: path
      required: true
      description: The last name of the user
      schema:
        $ref: "#/components/schemas/last_name"
    longitude:
      name: longitude
      in: path
      required: true
      description: The longitude status of the user
      schema:
        $ref: "#/components/schemas/coordinate"
    latitude:
      name: latitude
      in: path
      required: true
      description: The latitude status of the user
      schema:
        $ref: "#/components/schemas/coordinate"
    radius:
      name: radius
      in: path
      required: true
      description: A radius for a location search in miles
      schema:
        $ref: "#/components/schemas/radius"
    text:
      name: text
      in: path
      required: true
      description: Text to search for
      schema:
        $ref: "#/components/schemas/text"

  schemas:
    user_id:
      type: object
      properties:
        entityId:
          $ref: "#/components/schemas/id"

    users:
      type: array
      items:
        $ref: "#/components/schemas/user"

    user:
      allOf:
        - $ref: "#/components/schemas/user_full_name"
        - $ref: "#/components/schemas/user_age"
        - $ref: "#/components/schemas/user_verified"
        - $ref: "#/components/schemas/user_location"
        - $ref: "#/components/schemas/user_skills"
        - $ref: "#/components/schemas/user_statement"

    user_full_name:
      allOf:
        - $ref: "#/components/schemas/user_first_name"
        - $ref: "#/components/schemas/user_last_name"

    user_first_name:
      type: object
      properties:
        firstName:
          $ref: "#/components/schemas/first_name"

    user_last_name:
      type: object
      properties:
        lastName:
          $ref: "#/components/schemas/last_name"

    user_age:
      type: object
      properties:
        age:
          $ref: "#/components/schemas/age"

    user_verified:
      type: object
      properties:
        verified:
          $ref: "#/components/schemas/verified"

    user_location:
      allOf:
        - type: object
          properties:
            location:
              $ref: "#/components/schemas/location"
        - $ref: "#/components/schemas/user_location_updated"

    user_location_updated:
      type: object
      properties:
        locationUpdated:
          $ref: "#/components/schemas/location_updated"

    user_skills:
      type: object
      properties:
        skills:
          $ref: "#/components/schemas/skills"

    user_statement:
      type: object
      properties:
        useralStatement:
          $ref: "#/components/schemas/statement"

    id:
      description: The ID of the user
      type: string
      example: 01FX8N39YVZRCQNAW0R5T53H5T

    first_name:
      description: The given name of the user
      type: string
      example: Rupert

    last_name:
      description: The surname of the user
      type: string
      example: Holmes

    age:
      description: The age of the user in years
      type: integer
      format: int32
      example: 75

    verified:
      description: If the user has been verified
      type: boolean
      example: false

    location:
      description: The location of the user on the globe
      $ref: "#/components/schemas/geo"

    location_updated:
      description: >
        The date and time when the user last updated their location
        on the globe
      type: string
      format: date-time
      example: 2022-03-01T12:34:56.123Z

    skills:
      description: A list of skills that the user possesses
      type: array
      items:
        type: string
        example: dancing
      example:
        - singing
        - songwriting
        - playwriting

    statement:
      description: A statement about the user
      type: string
      example: I like piña coladas and walks in the rain

    text:
      description: Text to search for in human-readable text
      type: string
      example: walk

    geo:
      type: object
      required:
        - longitude
        - latitude
      properties:
        longitude:
          description: The longitudinal position on the globe
          $ref: "#/components/schemas/coordinate"
          example: -2.518
        latitude:
          description: The latitudinal position on the globe
          $ref: "#/components/schemas/coordinate"
          example: 53.259

    coordinate:
      description: >
        The longitudinal or latitudinal position on the globe
      type: number
      format: float
      example: 45.678

    radius:
      description: A radius, in miles
      type: integer
      format: int32
      example: 20
